# Generated by Django 5.2.8 on 2025-11-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_medicine_stock_alter_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
